Parameters:

    EnvironmentName:
        Description: This is the tag attached to the AWS account
        Type: String

    vpcCIDR:
        Description: This is the CIDR notation for the VPC
        Type: String
        Default: 12.0.0.0/16

    PublicSubnet1CIDR:
        Description: This is the public subnet 1 CIDR notation
        Type: String
        Default: 12.0.0.0/24

    PublicSubnet2CIDR:
        Description: This the public subnet 2 CIDR notation
        Type: String
        Default: 12.0.1.0/24

    PrivateSubnet1CIDR:
        Description: This is the private subnet 1 CIDR notation
        Type: String
        Default: 12.0.2.0/24

    PrivateSubnet2CIDR:
        Description: This is the private subnet 2 CIDR notation
        Type: String
        Default: 12.0.3.0/24

Resources:
    VPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: !Ref vpcCIDR
            Tags:
                - Key: name
                  Value: !Ref EnvironmentName

    InternetGateway:
        Type: AWS::EC2::InternetGateway
        Properties:
            Tags:
                - Key: name
                  Value: !Ref EnvironmentName

    InternetGatewayAttachment:
        Type: AWS::EC2::VPCGatewayAttachment
        Properties:
            InternetGatewayId: !Ref InternetGateway
            VpcId: !Ref VPC

    PublicSubnet1:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref VPC
            AvailabilityZone: !Select [ 0, !GetAZs '' ]
            CidrBlock: !Ref PublicSubnet1CIDR
            MapPublicIpOnLaunch: true
            Tags:
                - Key: name
                  Value: !Sub ${EnvironmentName} Public Subnet 1 (AZ1)

    PublicSubnet2:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref VPC
            AvailabilityZone: !Select [ 1, !GetAZs '' ]
            CidrBlock: !Ref PublicSubnet2CIDR
            MapPublicIpOnLaunch: true
            Tags:
                - Key: name
                  Value: !Sub ${EnvironmentName} Public Subnet 2 (AZ2)

    PrivateSubnet1:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref VPC
            AvailabilityZone: !Select [ 0, !GetAZs '' ]
            CidrBlock: !Ref PrivateSubnet1CIDR
            MapPublicIpOnLaunch: false
            Tags:
                - Key: name
                  Value: !Sub ${EnvironmentName} Private Subnet 1 (AZ1)

    PrivateSubnet2:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref VPC
            AvailabilityZone: !Select [ 1, !GetAZs '' ]
            CidrBlock: !Ref PrivateSubnet2CIDR
            MapPublicIpOnLaunch: false
            Tags:
                - Key: name
                  Value: !Sub ${EnvironmentName} Private Subnet 2 (AZ2)

    NatGateway1EIP:
        Type: AWS::EC2::EIP
        DependsOn: InternetGateway
        Properties:
            Domain: vpc

    NatGateway2EIP:
        Type: AWS::EC2::EIP
        DependsOn: InternetGateway
        Properties:
            Domain: vpc

    NatGateway1:
        Type: AWS::EC2::NatGateway
        Properties:
            AllocationId: !GetAtt NatGateway1EIP.AllocationId
            SubnetId: !Ref PublicSubnet1

    NatGateway2:
        Type: AWS::EC2::NatGateway
        Properties:
            AllocationId: !GetAtt NatGateway2EIP.AllocationId
            SubnetId: !Ref PublicSubnet2
